apiVersion: v1
kind: ServiceAccount
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
    tenant: TENANT_NAME
  annotations:
    # IRSA annotation will be added per environment
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ROLE_NAME

